# https://docs.flutter.dev/development/accessibility-and-localization/internationalization#adding-your-own-localized-messages
# https://docs.google.com/document/d/10e0saTfAv32OZLRmONy866vnaw0I2jwL8zukykpgWBc
arb-dir: lib/l10n
template-arb-file: intl_en.arb
synthetic-package: false
output-dir: lib/localization/intl
output-localization-file: messages.dart
output-class: FormBuilderLocalizationsImpl
nullable-getter: false
#untranslated-messages-file: build/untranslated-messages.txt