// coverage:ignore-file
import 'profanity.dart';

/// English profanity list.
class ProfanityDe extends Profanity {
  /// Creates a new instance of the profanity list.
  ProfanityDe([super.locale = 'de']);

  @override
  List<String> get profanityList => <String>[
        'analritter',
        'arsch',
        'arschficker',
        'arschlecker',
        'arschloch',
        'bimbo',
        'bratze',
        'bumsen',
        'bonze',
        'dödel',
        'fick',
        'ficken',
        'flittchen',
        'fotze',
        'fratze',
        'hackfresse',
        'hure',
        'hurensohn',
        'ische',
        'kackbratze',
        'kacke',
        'kacken',
        'kackwurst',
        'kampflesbe',
        'kanake',
        'kimme',
        'lümmel',
        'MILF',
        'möpse',
        'morgenlatte',
        'möse',
        'mufti',
        'muschi',
        'nackt',
        'neger',
        'nigger',
        'nippel',
        'nutte',
        'onanieren',
        'orgasmus',
        'penis',
        'pimmel',
        'pimpern',
        'pinkeln',
        'pissen',
        'pisser',
        'popel',
        'poppen',
        'porno',
        'reudig',
        'rosette',
        'schabracke',
        'schlampe',
        'scheiße',
        'scheisser',
        'schiesser',
        'schnackeln',
        'schwanzlutscher',
        'schwuchtel',
        'tittchen',
        'titten',
        'vögeln',
        'vollpfosten',
        'wichse',
        'wichsen',
        'wichser'
      ];
}
